// Package markdown renders an AnalysisResult as a structured Markdown document.
// It mirrors the HTML report's information — platform sections with architecture,
// traffic, DDD model, security, hotspots and longest functions — using plain text
// tables and headings with no CSS or JavaScript.
package markdown

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/exey/archscope/internal/git"
	"github.com/exey/archscope/internal/langspec"
	"github.com/exey/archscope/internal/modules"
	"github.com/exey/archscope/internal/parser"
	"github.com/exey/archscope/internal/result"
	"github.com/exey/archscope/internal/scanner"
	"github.com/exey/archscope/internal/security"
)

// Write renders res as Markdown and writes it to outPath.
func Write(res *result.AnalysisResult, outPath string) error {
	doc := Render(res)
	return os.WriteFile(outPath, []byte(doc), 0o644)
}

// Render returns the full Markdown document as a string.
func Render(res *result.AnalysisResult) string {
	var b strings.Builder

	// ── Document header ────────────────────────────────────────────────────────
	fmt.Fprintf(&b, "# ArchScope — %s\n\n", res.ProjectName)
	fmt.Fprintf(&b, "> Generated %s · %s files · %s lines\n\n",
		time.Now().Format("2006-01-02"),
		fmtNum(len(res.Files)),
		fmtNum(res.TotalLines()))

	if len(res.Technologies) > 0 {
		fmt.Fprintf(&b, "**Technologies:** %s\n\n", strings.Join(res.Technologies, " · "))
	}
	if len(res.DockerServices) > 0 {
		fmt.Fprintf(&b, "**Docker services:** %s\n\n", strings.Join(res.DockerServices, " · "))
	}

	b.WriteString("---\n\n")

	// ── Per-platform sections ──────────────────────────────────────────────────
	platforms := sortedPlatforms(res)
	for _, pg := range platforms {
		renderPlatform(&b, res, pg)
	}

	// ── CWE Index ─────────────────────────────────────────────────────────────
	b.WriteString(renderCWEIndexMD())

	// ── Footer ────────────────────────────────────────────────────────────────
	fmt.Fprintf(&b, "_Generated by [ArchScope v%s](https://github.com/Exey/archscope/tree/main) · Exey Panteleev · %s_\n",
		version, time.Now().Format("2006-01-02"))

	return b.String()
}

// renderPlatform writes one platform section (equivalent to one HTML tab).
func renderPlatform(b *strings.Builder, res *result.AnalysisResult, pg *scanner.PlatformGroup) {
	files := res.FilesForPlatform(pg.Platform)
	if len(files) == 0 {
		return
	}

	lines, decls := 0, 0
	for _, f := range files {
		lines += f.LineCount
		decls += len(f.Declarations)
	}

	fmt.Fprintf(b, "## %s\n\n", pg.TabLabel())
	fmt.Fprintf(b, "**%s files** · **%s lines** · **%s declarations** · **%d %s**\n\n",
		fmtNum(pg.FileCount), fmtNum(lines), fmtNum(decls),
		len(pg.Modules), plural(len(pg.Modules), "module", "modules"))

	// Render module sections using pre-computed results from the pipeline.
	// This avoids re-running Analyze and guarantees the same order as the HTML report.
	xfm := modules.NewTransformer()
	for _, panel := range res.ModulePanels {
		if panel.Platform != pg.Platform {
			continue
		}
		m := modules.Default.Get(panel.ModuleID)
		if m == nil {
			continue
		}
		xfm.Add(m, panel.RawResult)
	}
	if md := xfm.Markdown(); md != "" {
		b.WriteString(md)
	}

	// Microservices / Packages grid
	if s := renderMicroservicesMD(pg, files); s != "" {
		icon, label := langspec.Default.ModuleNoun(pg.Platform)
		fmt.Fprintf(b, "### %s %s\n\n", icon, label)
		b.WriteString(s)
	}

	// Module Penetration
	if s := renderPenetrationMD(files); s != "" {
		b.WriteString("### 🔗 Module Penetration\n\n")
		b.WriteString(s)
	}

	// TODOs & FIXMEs
	if s := renderTodosMD(files); s != "" {
		b.WriteString("### 📝 TODOs & FIXMEs\n\n")
		b.WriteString(s)
	}

	// Security findings
	if s := renderSecurityMD(res, pg.Platform); s != "" {
		b.WriteString("### 🔒 Security Findings\n\n")
		b.WriteString(s)
	}

	// Dependency hotspots
	if s := renderHotspotsMD(res, pg); s != "" {
		b.WriteString("### 🕸️ Dependency Hotspots\n\n")
		b.WriteString(s)
	}

	// Longest functions
	if s := renderLongestFuncsMD(files, res.RootPath); s != "" {
		b.WriteString("### 📏 Longest Functions\n\n")
		b.WriteString(s)
	}

	// Git Analysis — per-platform (churn + contributors filtered to platform files)
	if s := renderPlatformGitMD(res, pg, files); s != "" {
		b.WriteString(s)
	}

	// Modules & Microservices file inventory (platform-scoped)
	if s := renderModuleDetailsMD(res, files); s != "" {
		b.WriteString(s)
	}

	b.WriteString("---\n\n")
}

// ── Per-platform sections ─────────────────────────────────────────────────────

func renderMicroservicesMD(pg *scanner.PlatformGroup, files []*parser.ParsedFile) string {
	if len(pg.Modules) == 0 {
		return ""
	}
	counts := map[string]int{}
	mloc := map[string]int{}
	for _, f := range files {
		counts[f.ModuleName]++
		mloc[f.ModuleName] += f.LineCount
	}
	var b strings.Builder
	b.WriteString("| Module | Files | Lines |\n")
	b.WriteString("|--------|------:|------:|\n")
	for _, m := range pg.Modules {
		name := m
		if name == "" {
			name = "(root)"
		}
		fmt.Fprintf(&b, "| %s | %d | %s |\n", mdCell(name), counts[m], fmtNum(mloc[m]))
	}
	b.WriteString("\n")
	return b.String()
}

func renderPenetrationMD(files []*parser.ParsedFile) string {
	allMods := map[string]bool{}
	for _, f := range files {
		m := f.ModuleName
		if m == "" {
			m = "root"
		}
		allMods[m] = true
	}
	if len(allMods) < 2 {
		return ""
	}
	importedBy := map[string]map[string]bool{}
	for _, f := range files {
		src := f.ModuleName
		if src == "" {
			src = "root"
		}
		impLow := strings.ToLower(strings.Join(f.Imports, "\n"))
		for target := range allMods {
			if target == src {
				continue
			}
			if strings.Contains(impLow, strings.ToLower(target)) {
				if importedBy[target] == nil {
					importedBy[target] = map[string]bool{}
				}
				importedBy[target][src] = true
			}
		}
	}
	type row struct {
		name  string
		count int
		deps  []string
	}
	var rows []row
	for mod, deps := range importedBy {
		if len(deps) == 0 {
			continue
		}
		var dl []string
		for d := range deps {
			dl = append(dl, d)
		}
		sort.Strings(dl)
		rows = append(rows, row{mod, len(deps), dl})
	}
	if len(rows) == 0 {
		return ""
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].count > rows[j].count })
	if len(rows) > 15 {
		rows = rows[:15]
	}
	var b strings.Builder
	b.WriteString("| Module | Used by | Dependents |\n")
	b.WriteString("|--------|--------:|------------|\n")
	for _, r := range rows {
		deps := strings.Join(r.deps, ", ")
		if len(deps) > 80 {
			deps = deps[:77] + "…"
		}
		fmt.Fprintf(&b, "| %s | %d | %s |\n", mdCell(r.name), r.count, mdCell(deps))
	}
	b.WriteString("\n")
	return b.String()
}

func renderTodosMD(files []*parser.ParsedFile) string {
	modTodo := map[string]int{}
	modFixme := map[string]int{}
	for _, f := range files {
		m := f.ModuleName
		if m == "" {
			m = "root"
		}
		modTodo[m] += f.TodoCount
		modFixme[m] += f.FixmeCount
	}
	type row struct {
		name          string
		todos, fixmes int
	}
	var rows []row
	for m, t := range modTodo {
		fx := modFixme[m]
		if t+fx > 0 {
			rows = append(rows, row{m, t, fx})
		}
	}
	for m, fx := range modFixme {
		if modTodo[m] == 0 && fx > 0 {
			rows = append(rows, row{m, 0, fx})
		}
	}
	if len(rows) == 0 {
		return ""
	}
	sort.Slice(rows, func(i, j int) bool {
		return rows[i].todos+rows[i].fixmes > rows[j].todos+rows[j].fixmes
	})
	if len(rows) > 15 {
		rows = rows[:15]
	}
	var b strings.Builder
	b.WriteString("| Module | TODOs | FIXMEs |\n")
	b.WriteString("|--------|------:|-------:|\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "| %s | %d | %d |\n", mdCell(r.name), r.todos, r.fixmes)
	}
	b.WriteString("\n")
	return b.String()
}

func renderSecurityMD(res *result.AnalysisResult, plat langspec.Platform) string {
	platFiles := map[string]bool{}
	for _, f := range res.FilesForPlatform(plat) {
		platFiles[f.FilePath] = true
	}
	type row struct {
		sev  security.Severity
		rule string
		file string
		line int
	}
	var rows []row
	for _, rr := range res.Security {
		if rr.Passed() {
			continue
		}
		for _, f := range rr.Findings {
			if !platFiles[f.FullPath] {
				continue
			}
			rows = append(rows, row{rr.Rule.Severity, rr.Rule.Name, f.File, f.Line})
		}
	}
	if len(rows) == 0 {
		return ""
	}
	sort.Slice(rows, func(i, j int) bool {
		if rows[i].sev != rows[j].sev {
			return rows[i].sev.Rank() > rows[j].sev.Rank()
		}
		return rows[i].file < rows[j].file
	})
	if len(rows) > 30 {
		rows = rows[:30]
	}
	var b strings.Builder
	b.WriteString("| Severity | Rule | File | Line |\n")
	b.WriteString("|----------|------|------|-----:|\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "| %s | %s | %s | %d |\n",
			string(r.sev), mdCell(r.rule), mdCell(r.file), r.line)
	}
	b.WriteString("\n")
	return b.String()
}

func renderHotspotsMD(res *result.AnalysisResult, pg *scanner.PlatformGroup) string {
	inPlatform := map[string]bool{}
	for _, m := range pg.Modules {
		inPlatform[m] = true
	}
	folder := platformFolderSuffix(pg.Platform)
	qualify := func(name string) string {
		if folder == "" {
			return name
		}
		return name + "(" + folder + ")"
	}
	mloc := map[string]int{}
	mdecl := map[string]int{}
	for _, f := range res.FilesForPlatform(pg.Platform) {
		name := f.ModuleName
		if name == "" {
			name = "root"
		}
		mloc[name] += f.LineCount
		mdecl[name] += len(f.Declarations)
	}
	type row struct {
		name  string
		uses  int
		lines int
		decl  int
	}
	var rows []row
	for _, h := range res.Hotspots {
		if !inPlatform[h.Name] && !(h.Name == "root" && inPlatform[""]) {
			continue
		}
		rows = append(rows, row{h.Name, h.InDeg, mloc[h.Name], mdecl[h.Name]})
	}
	if len(rows) == 0 {
		return ""
	}
	sort.SliceStable(rows, func(i, j int) bool {
		if rows[i].uses != rows[j].uses {
			return rows[i].uses > rows[j].uses
		}
		return rows[i].lines > rows[j].lines
	})
	if len(rows) > 12 {
		rows = rows[:12]
	}
	var b strings.Builder
	b.WriteString("| Module | Dependents | Lines | Declarations |\n")
	b.WriteString("|--------|----------:|------:|-------------:|\n")
	for _, r := range rows {
		name := r.name
		if name == "root" {
			name = "(root)"
		} else {
			name = qualify(name)
		}
		fmt.Fprintf(&b, "| %s | %d | %s | %d |\n",
			mdCell(name), r.uses, fmtNum(r.lines), r.decl)
	}
	b.WriteString("\n")
	return b.String()
}

func renderLongestFuncsMD(files []*parser.ParsedFile, rootPath string) string {
	type entry struct{ fn *parser.FunctionInfo }
	var fns []entry
	for _, f := range files {
		if f.LongestFunc != nil && !isTestFile(f.FilePath) {
			fns = append(fns, entry{f.LongestFunc})
		}
	}
	if len(fns) == 0 {
		return ""
	}
	sort.Slice(fns, func(i, j int) bool { return fns[i].fn.LineCount > fns[j].fn.LineCount })
	if len(fns) > 15 {
		fns = fns[:15]
	}
	var b strings.Builder
	b.WriteString("| Function | Lines | File |\n")
	b.WriteString("|----------|------:|------|\n")
	for _, e := range fns {
		fn := e.fn
		rel := fn.FilePath
		if rootPath != "" {
			if r, err := filepath.Rel(rootPath, fn.FilePath); err == nil {
				rel = r
			}
		}
		file := rel
		if fn.StartLine > 0 {
			file = fmt.Sprintf("%s:%d", rel, fn.StartLine)
		}
		fmt.Fprintf(&b, "| %s | %d | %s |\n", mdCell(fn.Name), fn.LineCount, mdCell(file))
	}
	b.WriteString("\n")
	return b.String()
}

// ── Git Analysis ──────────────────────────────────────────────────────────────

func renderPlatformGitMD(res *result.AnalysisResult, pg *scanner.PlatformGroup, files []*parser.ParsedFile) string {
	g := res.Git
	if !g.Available {
		return ""
	}

	// Use the deepest matching git repo root so paths align with git log output.
	repoRoot := func(fp string) string {
		best := res.RootPath
		for _, repo := range g.Repos {
			if len(repo) > len(best) &&
				(strings.HasPrefix(fp, repo+string(filepath.Separator)) || fp == repo) {
				best = repo
			}
		}
		return best
	}

	platRel := map[string]bool{}
	for _, f := range files {
		root := repoRoot(f.FilePath)
		if r, err := filepath.Rel(root, f.FilePath); err == nil {
			platRel[r] = true
		}
	}

	var platChurn []git.FileChurnStat
	for _, c := range g.Churn {
		if platRel[c.RelPath] {
			platChurn = append(platChurn, c)
		}
	}

	platMods := map[string]bool{}
	for _, m := range pg.Modules {
		platMods[m] = true
		if m == "" {
			platMods["root"] = true
		}
	}
	type row struct {
		name    string
		commits int
		files   int
	}
	var authors []row
	for name, a := range g.Authors {
		for mod := range a.MicroserviceCounts {
			if platMods[mod] {
				authors = append(authors, row{name, a.TotalCommits, a.FilesModified})
				break
			}
		}
	}
	sort.Slice(authors, func(i, j int) bool {
		if authors[i].commits != authors[j].commits {
			return authors[i].commits > authors[j].commits
		}
		return authors[i].name < authors[j].name
	})
	if len(authors) > 10 {
		authors = authors[:10]
	}
	if len(platChurn) > 10 {
		platChurn = platChurn[:10]
	}

	var b strings.Builder
	b.WriteString("### 🐙 Git Analysis\n\n")

	if len(authors) > 0 {
		b.WriteString("**Top Contributors**\n\n")
		b.WriteString("| Author | Commits | Files |\n")
		b.WriteString("|--------|--------:|------:|\n")
		for _, r := range authors {
			fmt.Fprintf(&b, "| %s | %d | %d |\n", mdCell(r.name), r.commits, r.files)
		}
		b.WriteString("\n")
	}
	if len(platChurn) > 0 {
		b.WriteString("**File Churn**\n\n")
		b.WriteString("| File | Changes |\n")
		b.WriteString("|------|--------:|\n")
		for _, c := range platChurn {
			fmt.Fprintf(&b, "| %s | %d |\n", mdCell(c.RelPath), c.ChangeCount)
		}
		b.WriteString("\n")
	}

	// Releases & Commit Hygiene (repo-wide)
	t := g.Tags
	c := g.Commits
	fmt.Fprintf(&b, "**Releases:** %d tags · %d semver", t.TotalTags, t.SemverTags)
	if t.LatestSemver != "" {
		fmt.Fprintf(&b, " · latest `%s`", t.LatestSemver)
	}
	b.WriteString("\n\n")
	if c.Total > 0 {
		pct := c.Typed * 100 / c.Total
		fmt.Fprintf(&b, "**%d%%** conventional commits (%d/%d typed)\n\n", pct, c.Typed, c.Total)
	}

	// Branches (repo-wide)
	bs := g.Branch
	fmt.Fprintf(&b, "**Branches:** %d total", bs.TotalBranches)
	if bs.AvgLifetimeDays > 0 {
		fmt.Fprintf(&b, " · avg lifetime %.0f days", bs.AvgLifetimeDays)
	}
	b.WriteString("\n\n")
	if len(bs.StaleBranches) > 0 {
		stale := bs.StaleBranches
		if len(stale) > 5 {
			stale = stale[:5]
		}
		b.WriteString("| Stale branch | Days idle |\n")
		b.WriteString("|--------------|----------:|\n")
		for _, br := range stale {
			fmt.Fprintf(&b, "| %s | %d |\n", mdCell(br.Name), br.DaysInactive)
		}
		b.WriteString("\n")
	}

	return b.String()
}

func renderGitMD(g result.GitBundle) string {
	var b strings.Builder
	b.WriteString("## 🐙 Git Analysis\n\n")
	if !g.Available {
		b.WriteString("_No git history available._\n\n---\n\n")
		return b.String()
	}

	// Branching model
	m := g.Branch.Model
	fmt.Fprintf(&b, "### Branching Model\n\n**%s**", string(m.Model))
	if m.Confidence > 0 {
		fmt.Fprintf(&b, " · %d%% confidence · primary: `%s`", int(m.Confidence*100+0.5), g.Branch.PrimaryBranch)
	}
	b.WriteString("\n\n")
	if len(m.Signals) > 0 {
		for _, s := range m.Signals {
			fmt.Fprintf(&b, "- %s\n", s)
		}
		b.WriteString("\n")
	}

	// Top contributors
	if len(g.Authors) > 0 {
		type row struct {
			name    string
			commits int
			files   int
		}
		var rows []row
		for name, a := range g.Authors {
			rows = append(rows, row{name, a.TotalCommits, a.FilesModified})
		}
		sort.Slice(rows, func(i, j int) bool {
			if rows[i].commits != rows[j].commits {
				return rows[i].commits > rows[j].commits
			}
			return rows[i].name < rows[j].name
		})
		if len(rows) > 10 {
			rows = rows[:10]
		}
		b.WriteString("### Top Contributors\n\n")
		b.WriteString("| Author | Commits | Files |\n")
		b.WriteString("|--------|--------:|------:|\n")
		for _, r := range rows {
			fmt.Fprintf(&b, "| %s | %d | %d |\n", mdCell(r.name), r.commits, r.files)
		}
		b.WriteString("\n")
	}

	// File churn
	if len(g.Churn) > 0 {
		churn := g.Churn
		if len(churn) > 10 {
			churn = churn[:10]
		}
		b.WriteString("### File Churn\n\n")
		b.WriteString("| File | Changes |\n")
		b.WriteString("|------|--------:|\n")
		for _, c := range churn {
			fmt.Fprintf(&b, "| %s | %d |\n", mdCell(c.RelPath), c.ChangeCount)
		}
		b.WriteString("\n")
	}

	// Tags & commit hygiene
	t := g.Tags
	c := g.Commits
	b.WriteString("### Releases & Commit Hygiene\n\n")
	fmt.Fprintf(&b, "**%d tags** · %d semver", t.TotalTags, t.SemverTags)
	if t.LatestSemver != "" {
		fmt.Fprintf(&b, " · latest `%s`", t.LatestSemver)
	}
	b.WriteString("\n\n")
	if len(t.SemverList) > 0 {
		lim := t.SemverList
		if len(lim) > 12 {
			lim = lim[:12]
		}
		fmt.Fprintf(&b, "Tags: %s\n\n", strings.Join(lim, " · "))
	}
	if c.Total > 0 {
		pct := c.Typed * 100 / c.Total
		fmt.Fprintf(&b, "**%d%%** conventional commits (%d/%d typed)\n\n", pct, c.Typed, c.Total)
		if len(c.TypeCounts) > 0 {
			type kv struct{ k string; v int }
			var kvs []kv
			for k, v := range c.TypeCounts {
				kvs = append(kvs, kv{k, v})
			}
			sort.Slice(kvs, func(i, j int) bool { return kvs[i].v > kvs[j].v })
			parts := make([]string, 0, len(kvs))
			for _, p := range kvs {
				parts = append(parts, fmt.Sprintf("%s · %d", p.k, p.v))
			}
			fmt.Fprintf(&b, "Types: %s\n\n", strings.Join(parts, " · "))
		}
	}

	// Branches
	bs := g.Branch
	fmt.Fprintf(&b, "### Branches\n\n**%d total**", bs.TotalBranches)
	if bs.AvgLifetimeDays > 0 {
		fmt.Fprintf(&b, " · avg lifetime %.0f days", bs.AvgLifetimeDays)
	}
	if bs.PeakCommitDay != "" {
		fmt.Fprintf(&b, " · peak day %s", bs.PeakCommitDay)
	}
	b.WriteString("\n\n")
	if len(bs.StaleBranches) > 0 {
		stale := bs.StaleBranches
		if len(stale) > 8 {
			stale = stale[:8]
		}
		b.WriteString("| Stale branch | Days idle |\n")
		b.WriteString("|--------------|----------:|\n")
		for _, br := range stale {
			fmt.Fprintf(&b, "| %s | %d |\n", mdCell(br.Name), br.DaysInactive)
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n\n")
	return b.String()
}

// ── Modules & Microservices ───────────────────────────────────────────────────

func renderModuleDetailsMD(res *result.AnalysisResult, platformFiles []*parser.ParsedFile) string {
	type mod struct {
		name  string
		plat  langspec.Platform
		ptype string
		files []*parser.ParsedFile
		lines int
		decls int
	}
	order := []string{}
	mods := map[string]*mod{}
	for _, f := range platformFiles {
		m := mods[f.ModuleName]
		if m == nil {
			m = &mod{name: f.ModuleName, plat: langspec.Platform(f.Platform), ptype: f.ProjectType}
			mods[f.ModuleName] = m
			order = append(order, f.ModuleName)
		}
		m.files = append(m.files, f)
		m.lines += f.LineCount
		m.decls += len(f.Declarations)
		if m.ptype == "" {
			m.ptype = f.ProjectType
		}
	}
	if len(mods) == 0 {
		return ""
	}
	list := make([]*mod, 0, len(mods))
	for _, n := range order {
		list = append(list, mods[n])
	}
	sort.SliceStable(list, func(i, j int) bool {
		if list[i].lines != list[j].lines {
			return list[i].lines > list[j].lines
		}
		return list[i].name < list[j].name
	})

	var b strings.Builder
	b.WriteString("## 📂 Modules & Microservices\n\n")

	for _, m := range list {
		name := m.name
		if name == "" {
			name = "(root)"
		}
		badge := ""
		if m.ptype != "" {
			badge = " · " + m.ptype
		}
		fmt.Fprintf(&b, "### %s%s\n\n", name, badge)
		fmt.Fprintf(&b, "%d files · %s lines · %d declarations\n\n",
			len(m.files), fmtNum(m.lines), m.decls)

		// Filter files same as HTML renderer, with TS/JS 15-line minimum.
		all := append([]*parser.ParsedFile(nil), m.files...)
		sort.SliceStable(all, func(i, j int) bool { return all[i].LineCount > all[j].LineCount })

		var keep []*parser.ParsedFile
		for _, f := range all {
			if isGeneratedFile(f.FilePath) {
				continue
			}
			if isTestFile(f.FilePath) {
				continue
			}
			if f.LanguageID == "ts" && f.LineCount < 15 {
				continue
			}
			if len(f.Declarations) == 0 && f.LineCount < 30 {
				continue
			}
			keep = append(keep, f)
		}
		if len(keep) == 0 {
			continue
		}

		b.WriteString("| File | Lines | Decl | Declarations |\n")
		b.WriteString("|------|------:|-----:|-------------|\n")
		for _, f := range keep {
			rel := f.FilePath
			if res.RootPath != "" {
				if r, err := filepath.Rel(res.RootPath, f.FilePath); err == nil {
					rel = r
				}
			}
			declNames := declListMD(f.Declarations, 8)
			fmt.Fprintf(&b, "| %s | %d | %d | %s |\n",
				mdCell(rel), f.LineCount, len(f.Declarations), mdCell(declNames))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// declListMD returns a comma-joined list of up to n declaration names.
func declListMD(decls []parser.Declaration, n int) string {
	if len(decls) == 0 {
		return ""
	}
	names := make([]string, 0, n)
	for i, d := range decls {
		if i >= n {
			names = append(names, fmt.Sprintf("+%d", len(decls)-n))
			break
		}
		names = append(names, d.Name)
	}
	return strings.Join(names, ", ")
}

// ── Platform ordering ─────────────────────────────────────────────────────────

// sortedPlatforms returns platforms in the same order as the HTML tab renderer.
func sortedPlatforms(res *result.AnalysisResult) []*scanner.PlatformGroup {
	platforms := res.Scan.PlatformsOrdered()
	loc := map[langspec.Platform]int{}
	for _, f := range res.Files {
		loc[langspec.Platform(f.Platform)] += f.LineCount
	}
	platforms = append([]*scanner.PlatformGroup(nil), platforms...)
	if res.Scan.FolderAsTab {
		folderLOC := map[string]int{}
		for _, pg := range platforms {
			folderLOC[tabFolder(pg.Platform)] += loc[pg.Platform]
		}
		sort.SliceStable(platforms, func(i, j int) bool {
			fi, fj := tabFolder(platforms[i].Platform), tabFolder(platforms[j].Platform)
			if fi != fj {
				li, lj := folderLOC[fi], folderLOC[fj]
				if li != lj {
					return li > lj
				}
				return fi < fj
			}
			return platforms[i].TabLabel() < platforms[j].TabLabel()
		})
	} else {
		sort.SliceStable(platforms, func(i, j int) bool {
			li, lj := loc[platforms[i].Platform], loc[platforms[j].Platform]
			if li != lj {
				return li > lj
			}
			return platforms[i].FileCount > platforms[j].FileCount
		})
	}
	return platforms
}

// ── Helpers ───────────────────────────────────────────────────────────────────


func mdCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}

func platformFolderSuffix(p langspec.Platform) string {
	s := string(p)
	if i := strings.IndexByte(s, ':'); i >= 0 {
		return s[i+1:]
	}
	return ""
}

func tabFolder(p langspec.Platform) string {
	s := string(p)
	if i := strings.IndexByte(s, ':'); i >= 0 {
		return s[i+1:]
	}
	return s
}

func isTestFile(path string) bool {
	lower := strings.ToLower(filepath.ToSlash(path))
	return strings.HasSuffix(lower, "_test.go") ||
		strings.Contains(lower, "/test/") ||
		strings.Contains(lower, "/__tests__/") ||
		strings.HasPrefix(filepath.Base(lower), "test_")
}

func isGeneratedFile(path string) bool {
	base := filepath.Base(path)
	return strings.HasSuffix(base, ".pb.go") || strings.HasPrefix(base, "zz_generated")
}

func fmtNum(n int) string {
	s := fmt.Sprintf("%d", n)
	if n < 1000 {
		return s
	}
	var out []byte
	for i, ch := range s {
		if i > 0 && (len(s)-i)%3 == 0 {
			out = append(out, ',')
		}
		out = append(out, byte(ch))
	}
	return string(out)
}

func plural(n int, sing, plur string) string {
	if n == 1 {
		return sing
	}
	return plur
}

// ── CWE Index ─────────────────────────────────────────────────────────────────

func renderCWEIndexMD() string {
	type cweRow struct {
		num       int
		names     []string // deduplicated rule names
		count     int      // number of distinct rules mapped to this CWE
		severity  security.Severity
		langs     []string // display names
		universal bool     // true if any rule for this CWE is language-universal
	}
	byCWE := map[int]*cweRow{}
	langLabel := map[string]string{
		"go": "Go", "python": "Python", "swift": "Swift",
		"kotlin": "Kotlin", "ts": "TS/JS",
	}
	for _, r := range security.Default.Rules() {
		if r.CWE == "" {
			continue
		}
		n, err := strconv.Atoi(r.CWE)
		if err != nil {
			continue
		}
		row := byCWE[n]
		if row == nil {
			row = &cweRow{num: n, severity: r.Severity}
			byCWE[n] = row
		}
		row.count++
		// Deduplicate rule names.
		found := false
		for _, existing := range row.names {
			if existing == r.Name {
				found = true
				break
			}
		}
		if !found && r.Name != "" {
			row.names = append(row.names, r.Name)
		}
		// Track language coverage.
		if len(r.Languages) == 0 {
			row.universal = true
		} else {
			for _, lid := range r.Languages {
				label := langLabel[lid]
				if label == "" {
					label = lid
				}
				already := false
				for _, l := range row.langs {
					if l == label {
						already = true
						break
					}
				}
				if !already {
					row.langs = append(row.langs, label)
				}
			}
		}
		// Promote severity to highest seen.
		if r.Severity.Rank() > row.severity.Rank() {
			row.severity = r.Severity
		}
	}
	if len(byCWE) == 0 {
		return ""
	}
	rows := make([]*cweRow, 0, len(byCWE))
	for _, r := range byCWE {
		rows = append(rows, r)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].num < rows[j].num })

	cweDesc := map[int]string{
		16:   "Security Configuration Errors",
		22:   "Path Traversal",
		78:   "OS Command Injection",
		79:   "Cross-Site Scripting",
		89:   "SQL Injection",
		94:   "Code Injection",
		117:  "Log Output Neutralization",
		119:  "Buffer Overflow",
		272:  "Least Privilege Violation",
		276:  "Incorrect Default Permissions",
		295:  "Improper Certificate Validation",
		311:  "Missing Encryption of Sensitive Data",
		319:  "Cleartext Transmission",
		321:  "Hard-coded Cryptographic Key",
		327:  "Broken or Risky Crypto Algorithm",
		328:  "Weak Hash",
		329:  "Not Using Random IV with CBC Mode",
		338:  "Cryptographically Weak PRNG",
		346:  "Origin Validation Error",
		347:  "Improper Cryptographic Signature Check",
		352:  "Cross-Site Request Forgery",
		362:  "Race Condition (TOCTOU)",
		400:  "Uncontrolled Resource Consumption",
		434:  "Unrestricted File Upload",
		476:  "NULL Pointer Dereference",
		477:  "Use of Obsolete Function",
		489:  "Active Debug Code",
		502:  "Deserialization of Untrusted Data",
		522:  "Insufficiently Protected Credentials",
		530:  "Exposure of Backup File",
		532:  "Sensitive Info in Log File",
		601:  "URL Redirection to Untrusted Site",
		611:  "XML External Entity (XXE)",
		614:  "Sensitive Cookie Without Secure Flag",
		693:  "Protection Mechanism Failure",
		732:  "Incorrect Permission Assign for Crit. Resource",
		749:  "Exposed Dangerous Method",
		770:  "Allocation of Resources Without Limits",
		798:  "Hard-coded Credentials",
		913:  "Improper Control of Dynamic-Managed Code",
		916:  "Weak Password Hash Algorithm",
		918:  "Server-Side Request Forgery",
		922:  "Insecure Storage of Sensitive Info",
		926:  "Improper Export of Android Components",
		942:  "Permissive CORS Policy",
		943:  "NoSQL Injection",
		1004: "Sensitive Cookie Without HttpOnly Flag",
		1321: "Prototype Pollution",
		1299: "Missing Protection for Alternate Hardware",
		1333: "Regular Expression DoS",
		1336: "Server-Side Template Injection",
	}

	var b strings.Builder
	b.WriteString("## 🔐 Security Coverage — CWE Index\n\n")
	fmt.Fprintf(&b, "%d distinct CWEs covered across all languages.\n\n", len(rows))
	b.WriteString("| CWE | Vulnerability | Checks | Severity | Languages |\n")
	b.WriteString("|-----|---------------|-------:|----------|-----------|\n")
	for _, r := range rows {
		desc := cweDesc[r.num]
		if desc == "" {
			desc = strings.Join(r.names, " / ")
		}
		if desc == "" {
			desc = "—"
		}
		langs := "all"
		if !r.universal && len(r.langs) > 0 {
			sort.Strings(r.langs)
			langs = strings.Join(r.langs, ", ")
		}
		fmt.Fprintf(&b, "| [CWE-%d](https://cwe.mitre.org/data/definitions/%d.html) | %s | %d | %s | %s |\n",
			r.num, r.num, mdCell(desc), r.count, string(r.severity), langs)
	}
	b.WriteString("\n---\n\n")
	return b.String()
}

const version = "1.0.0"

// Ensure git import is used (referenced via result.GitBundle).
var _ git.AuthorStats
