// Package html renders an AnalysisResult to a single self-contained HTML file:
// global summary cards, a CSS-only platform tab bar (one tab per platform
// present), per-platform sections (modules, dependency hotspots, security
// findings, and language/universal report-module panels), and a repo-wide git
// section below the tabs. It imports the shared theme from package report and
// is the only place that knows the document's overall shape.
package html

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/exey/archscope/internal/report"
	"github.com/exey/archscope/internal/result"
)

// Write renders res to a complete HTML document at outPath.
func Write(res *result.AnalysisResult, outPath string) error {
	doc := Render(res)
	return os.WriteFile(outPath, []byte(doc), 0o644)
}

// Render returns the full HTML document as a string (separated from Write so it
// is trivially unit-testable).
func Render(res *result.AnalysisResult) string {
	var b strings.Builder
	b.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\">")
	b.WriteString(`<meta name="viewport" content="width=device-width,initial-scale=1">`)
	fmt.Fprintf(&b, "<title>ArchScope — %s</title>", esc(res.ProjectName))
	b.WriteString("<style>")
	b.WriteString(report.CSS)
	b.WriteString("</style>")
	// Async loader: loads d3-force then force-graph from CDN. Each graph script
	// registers [initFn, fallbackFn] in window.__asgq; the loader calls the
	// right one after load succeeds, fails, or times out (9 s).
	b.WriteString(`<script>(function(){` +
		`var q=window.__asgq=[],done=false;` +
		`function run(ok){if(done)return;done=true;` +
		`q.forEach(function(p){try{ok?p[0]():p[1]();}catch(e){try{p[1]();}catch(e2){}}});}` +
		`var t=setTimeout(function(){run(false);},9000);` +
		`function ld(u,s,e){var x=document.createElement('script');x.src=u;x.onload=s;x.onerror=e;document.head.appendChild(x);}` +
		`ld('https://unpkg.com/d3-force@3',` +
		`function(){ld('https://unpkg.com/force-graph',` +
		`function(){clearTimeout(t);run(true);},` +
		`function(){clearTimeout(t);run(false);});},` +
		`function(){clearTimeout(t);run(false);}` +
		`);})()` +
		`</script>`)
	b.WriteString("</head><body><div class=\"as-wrap\">")

	// Header
	b.WriteString(`<div class="as-head"><div class="as-head__title">`)
	b.WriteString(`<span class="as-brand">🏛️🔬 ArchScope </span>`)
	fmt.Fprintf(&b, `<h1>%s</h1>`, esc(res.ProjectName))
	b.WriteString(`</div>`)
	b.WriteString(`<button id="as-theme-toggle" class="as-toggle">☀ Light</button>`)
	b.WriteString(`</div>`)

	// Source line
	src := res.RootPath
	if res.IsRemote && res.SourceURL != "" {
		src = res.SourceURL
	}
	langs := strings.Join(res.Scan.ProjectTypes, ", ")
	fmt.Fprintf(&b, `<div class="as-sourceline">%s%s</div>`,
		esc(src), projectTypeSuffix(langs))

	// Global cards
	b.WriteString(renderGlobalCards(res))

	// Tech stack + packages & modules (repo-wide)
	b.WriteString(renderStackAndModules(res))

	// Global architecture graph (modules + tech nodes)
	b.WriteString(renderGlobalArchGraph(res))

	// Global security index (gauge + categories)
	b.WriteString(renderSecurityIndex(res))

	// Platform tabs
	b.WriteString(renderTabs(res))

	// Repo-wide git section
	b.WriteString(renderGit(res))

	// Bottom: detailed per-module / per-microservice breakdown
	b.WriteString(renderModuleDetails(res))

	// Footer
	fmt.Fprintf(&b, `<div class="as-foot">Generated by <a href="https://github.com/Exey/archscope">ArchScope</a> v%s · Exey Panteleev · %s</div>`,
		report.Version, time.Now().Format("2006-01-02 15:04"))

	b.WriteString(`</div><script>`)
	b.WriteString(report.JS)
	b.WriteString(`</script></body></html>`)
	return b.String()
}

func projectTypeSuffix(langs string) string {
	if strings.TrimSpace(langs) == "" {
		return ""
	}
	return "  ·  " + esc(langs)
}
